### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by NitroGhost** [electron/node-rcedit#11]
is there a way to change the language code using this? in the resource file there's:

    BLOCK "VarFileInfo"
    {
        VALUE "Translation", 0x0409 0x04B0
    }

where 0x0409 is the English (United States) code

need to change the language to my countries lang

**Comment by kevinsawicki** [comment]
This is a duplicate of https://github.com/electron/rcedit/issues/18, closing this out and tracking the issue there.
