### ISSUE TITLE
node-rcedit don't rise and error if binary rcedit rises missing dll error

### ISSUE THREAD

**Issue by tyv** [electron/node-rcedit#12]
I spent a lot of time trying to figure out what is going on.
If you miss `msvcp120.dll` which is common problem for [Windows](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=msvcp120+dll+windows+8.1+32+bit) the `rcedit.exe` will rise that error, but `node-rcedit` not.

**Comment by dhildebrandt** [comment]
I hope it's not inappropriate for me to add a 'me, too' kind of post to this.

**Comment by kevinsawicki** [comment]
I believe this was addressed by https://github.com/electron/rcedit/pull/11 and is no longer an issue on the latest release, 0.6.0
