### ISSUE TITLE
Add Warnings when wine Version Lower than 1.6

### ISSUE THREAD

**Issue by evshiron** [electron/node-rcedit#15]
I was using Travis CI to do automatic testing and suddenly everything failed after the required wine version grew.
By digging into the logs I discover the wine version used is 1.4, but after I switch to `ppa:wine/wine-builds` and `winehq-devel` 1.9, the situation doesn't change. I fix this by fixing`rcedit` version to 0.5.0 in `package.json`. But a warning will always be a good thing.
BTW don't think this is a minor change.

**Comment by malept** [comment]
Wine 1.6 is pretty old at this point so I don't think we need to do this anymore.
