### ISSUE TITLE
Add support for wine64

### ISSUE THREAD

**Issue by malept** [electron/node-rcedit#22]
In https://github.com/electron-userland/electron-packager/issues/519 someone asked to be able to use wine64 to run `rcedit.exe`. My suggestion is to use `process.env.WINE || 'wine'` and add a `WINE=wine64` env to the Travis build matrix.

**Comment by malept** [comment]
It might be more work than I initially wrote in the issue summary. On Debian amd64, I only have wine64 installed, but there's a `wine` script that points to wine64. This is the error I get when I try to run node-rcedit:

```
rcedit.exe failed with exit code 193. wine: Bad EXE format for Z:\tmp\test\electron-packager\node_modules\rcedit\bin\rcedit.exe.
```

It looks like for it to work on wine64, there also needs to be a 64-bit build of `rcedit.exe` as well.

**Comment by rherrick** [comment]
It looks like rcedit now has a 64-bit executable rcedit-x64.exe. Is it possible to perform Windows code signing with 64-bit wine?

**Comment by dfeinzeig** [comment]
So we should still be using wine32?
