### ISSUE TITLE
Do we have a way to remove unwanted version string like "Original File Name"?

### ISSUE THREAD

**Issue by caracare521** [electron/node-rcedit#24]
Just want to know if there is some method to remove a certain version string.

**Comment by pablozandona** [comment]
+1

**Comment by pablozandona** [comment]
For edit do you need set OriginalFilename:

'version-string': {
            CompanyName: 'CompanyName',
            FileDescription: 'FileDescription',
            LegalCopyright: 'Copyright 2017',
            ProductName: 'ProductName',
            OriginalFilename: 'OriginalFilename'
        }

**Comment by malept** [comment]
You should just be able to set an empty string.
