### ISSUE TITLE
rcedit failed - unable to commit changes

### ISSUE THREAD

**Issue by hlfshell** [electron/node-rcedit#25]
I've opened a similar issue on the [electron-packager GitHub](https://github.com/electron-userland/electron-packager/issues/590), specifically because I am unsure if there is a problem with rcedit or electron-packager's passing of parameters to rcedit. Unfortunately the error messaging is vague and I'm at a loss of where to go from here.

I keep getting the following when using electron-packager:

```
λ electron-packager . app --platform=win32 --arch=x64
Packaging app for platform win32 x64 using electron v1.4.13
rcedit.exe failed with exit code 1. Fatal error: Unable to commit changes
```

I've ensured that rcedit was downloaded by electron-packager, and even placed rcedit in my path just in case and got the same error. Unfortunately, the error is very vague and I'm not sure how to debug it.

**Comment by hlfshell** [comment]
Per the [referenced issue here](https://github.com/electron-userland/electron-packager/issues/590), this issue has been determined to be the result of an over zealous virus scanner on a corporate network and, for now, can safely be assumed to be resolved.

**Comment by russlamb** [comment]
i'm having this issue as well.  do you have any workaround for resolving it?  

I don't see any anti-virus on my machine but am on a corporate network so maybe there is something in the background.
