### ISSUE TITLE
packager in electron's asar error

### ISSUE THREAD

**Issue by tianxiangbing** [electron/node-rcedit#33]
"spawn E:\git\mock\out\mock-win32-x64\resources\app.asar\node_modules\rcedit\bin\rcedit.exe ENOENT"

**Comment by malept** [comment]
Are you trying to use the `rcedit` module inside of an Electron app?

**Comment by tianxiangbing** [comment]
@malept yes,
Can I integrate it into my electron project?

**Comment by malept** [comment]
Yes, but you need to exclude it from your app's asar file with asar's unpackDir option.
