### ISSUE TITLE
After change icon the exe file become invalid

### ISSUE THREAD

**Issue by EasonWang01** [electron/node-rcedit#35]
```
pkg ./test.js --output test.exe
```
then it works good.

Change the icon :
```js
const rcedit = require('rcedit')
const fs = require('fs')
const filename = './test.exe'

console.log(fs.existsSync(filename))

rcedit(filename , {
  icon: './png/003_snorlax_Fxe_icon.ico'
},(err) => {
  console.log(err)
})
```

then execute the program again it will result an error:
```
Pkg: Error reading from file.
```

**Comment by goldalworming** [comment]
me too.. I hope there is solution for this

**Comment by m4heshd** [comment]
Yup. The executable won't run anymore.

**Comment by malept** [comment]
This is really a bug upstream in [`electron/rcedit`](https://github.com/electron/rcedit), as all of the EXE-modifying logic is there, so I'm closing it here.
