### ISSUE TITLE
The application has failed to start because its side-by-side configuration is incorrect

### ISSUE THREAD

**Issue by tgds** [electron/node-rcedit#36]
![image](https://user-images.githubusercontent.com/9978312/36558698-26d5ae10-180c-11e8-99fa-13d4f8cb9546.png)

Getting the above error on Windows 10, after running rcedit with the following option:

`{ "requested-execution-level": "requireAdministrator" }`

**Comment by malept** [comment]
This might be the same problem as https://github.com/electron/rcedit/issues/51

**Comment by malept** [comment]
Closing this because there's an issue upstream.
