### ISSUE TITLE
sync with npm

### ISSUE THREAD

**Issue by andreineculau** [electron/node-rcedit#49]
the master branch's package.json says "1.1.1", but github releases has 1.1.2 and 2.0.0

**Comment by malept** [comment]
This is because we're now using semantic-release. To prevent further confusion, the version in git should be 0.0.0-development

**Comment by andreineculau** [comment]
:+1: I see. Didn't know that. As I didn't know anything about semantic-release.
I found out from https://github.com/semantic-release/semantic-release/issues/497 that there is git plugin now https://github.com/semantic-release/git that can actually bump the version in package.json but I fully understand if it's too much to ask.

I understand the "forces" of semantic-release not bumping and and pushing by default (requires git permissions), but overall it's an unfortunate design because it prevents forking the source-code and "it just works". Now you need out-of-bound information as to which commit has been released in which version. And as more practical example with npm: doing `npm i git://github.com/electron/node-rcedit#82b9925` (82b9925 is the latest commit on master right now) will actually tell npm that I have installed node-rcedit v1.1.1 (or somewhere in the vicinity), and not v2.0.0, which can be 💣 waiting to go 💥 .

Anyways, thanks for answering.
