### ISSUE TITLE
macOS Catalina: wine doesn't work

### ISSUE THREAD

**Issue by antelle** [electron/node-rcedit#51]
Hi! 

Looks like `wine` doesn't work on macOS Catalina: https://forum.winehq.org/viewtopic.php?f=9&t=32590

```
% wine
zsh: bad CPU type in executable: wine
```

So, this package throws an error indeed. Example: https://github.com/electron/electron-packager/issues/1055

Would be nice to find a mitigation.

**Comment by MarshallOfSound** [comment]
This is an issue with your install of `wine`, Catalina disables 32bit applications

**Comment by malept** [comment]
@MarshallOfSound I think the answer is to add the x64 binary to node-rcedit (#50).

**Comment by antelle** [comment]
It won't work, because there's no x64 version of wine for mac.

**Comment by malept** [comment]
Then I suppose the workaround is to either run Windows in a VM, or Linux (with Wine) in a VM.

**Comment by cap10morgan** [comment]
When I install wine on my Mac via Homebrew, I get a `/usr/local/bin/wine64` that works. If there were a 64-bit version of rcedit.exe, it would likely work with that wine binary.

**Comment by alexluoli** [comment]
1. brew upgrade wine, make sure "/usr/local/bin/wine64" exist
2. rm -rf ~/.wine
3. edit "node_modules/rcedit/lib/rcedit.js", change "wine" to "wine64" at line 42
4. download "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe", rename to "rcedit.exe" and replace "node_modules/rcedit/bin/rcedit.exe"

It works!!!

**Comment by maximilianschmidt** [comment]
thanks @alexluoli, works like a charme. i didn't even had to follow step 2 (`rm -rf ~/.wine`).

**Comment by AndreiSoroka** [comment]
@alexluoli @maximilianschmidt can you write more details, please.
I'm from https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/468#issuecomment-546386309

**Comment by maximilianschmidt** [comment]
@AndreiSoroka you should target the `node_modules` folder in your project

**Comment by AndreiSoroka** [comment]
@maximilianschmidt oh, but I didn't have rcedit.
```
 "dependencies": {
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.4",
    "core-js": "^3.3.2",
    "cpisn": "^1.0.1",
    "node-fetch": "^2.6.0",
    "universal-analytics": "^0.4.20",
    "vue": "^2.6.10",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^4.0.0",
    "@vue/cli-plugin-eslint": "^4.0.0",
    "@vue/cli-plugin-vuex": "^4.0.0",
    "@vue/cli-service": "^4.0.0",
    "@vue/eslint-config-airbnb": "^4.0.0",
    "babel-eslint": "^10.0.3",
    "electron": "^6.0.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "lint-staged": "^9.4.2",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "vue-cli-plugin-electron-builder": "^1.4.0",
    "vue-template-compiler": "^2.6.10"
  },
```
rcedit should be in the dependencies on vue-cli-plugin-electron-builder?

**Comment by maximilianschmidt** [comment]
@AndreiSoroka i think its a peer-dependency and thus not listed in the package.json. just use Finder for navigating to `/node_modules/rcedit`

**Comment by AndreiSoroka** [comment]
@maximilianschmidt yep.
I checked: `./node_modules/**`
And not found

**Comment by antelle** [comment]
Nice, question to authors: what about rebuilding the package? 😉

**Comment by paul321** [comment]
Why isn't anyone updating this repo with rcedit-x64 if that is the solution?

**Comment by jafri** [comment]
@zcbenz @kevinsawicki this is a stopping issue for building .exe on macs

**Comment by charmer1989** [comment]
1. brew install homebrew/cask/wine-stable     Then  mv /usr/local/bin/wine64 /usr/local/bin/wine

2. download "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe", rename to "rcedit.exe" and replace "node_modules/rcedit/bin/rcedit.exe"  (Thanks from https://github.com/electron/node-rcedit/issues/51#issuecomment-546234084)

It works!!!

**Comment by esigalas** [comment]
>    ... and replace "node_modules/rcedit/bin/rcedit.exe"  ...

can I ask what is the full path for that file?
thanks

**Comment by unbreakableglass** [comment]
> > ... and replace "node_modules/rcedit/bin/rcedit.exe"  ...
> 
> can I ask what is the full path for that file?
> thanks

/usr/local/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe

**Comment by esigalas** [comment]
now I think I am confused
why do I need to have npm installed?

**Comment by esigalas** [comment]
> > > ... and replace "node_modules/rcedit/bin/rcedit.exe"  ...
> > 
> > 
> > can I ask what is the full path for that file?
> > thanks
> 
> /usr/local/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe

now I am confused
why do I have to have npm installed?

**Comment by kylekrzeski** [comment]
> 1. brew install homebrew/cask/wine-stable     Then  mv /usr/local/bin/wine64 /usr/local/bin/wine
> 2. download "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe", rename to "rcedit.exe" and replace "node_modules/rcedit/bin/rcedit.exe"  (Thanks from [#51 (comment)](https://github.com/electron/node-rcedit/issues/51#issuecomment-546234084))
> 
> It works!!!

rcedit wasn't in my project or /usr/local/lib/node_modules. I tried npm installing it and doing those steps though that didn't seem to work. Any idea what to do if it's not there?

**Comment by esigalas** [comment]
ok actually I found a solution to my problem.

I have installed wine-stable using brew cask.
when I run the wine command I get the known error
`% wine

zsh: bad CPU type in executable: wine
`

but there is a proper binary installed as well, so I just used the command wine64 instead

**Comment by esigalas** [comment]
ok actually I found a solution to my problem.

I have installed wine-stable using brew cask.
when I run the `wine` command I get the known error
`% wine zsh: bad CPU type in executable: wine`

but there is a proper binary installed as well, so I just used the command `wine64` instead

**Comment by unhuman** [comment]
or just alias `wine` to `wine64`

**Comment by daron4ever** [comment]
> After you homebrew, just alias `wine` to `wine64`
> 
> It won't run 32 bit apps though.

How to create the alias?

**Comment by hggz** [comment]
> After you homebrew, just alias `wine` to `wine64`
> 
> It won't run 32 bit apps though.

my life is meaningless

**Comment by getmahbub** [comment]
`wine64 start` instate of `wine start`

**Comment by OlyDLG** [comment]
> 1. brew upgrade wine, make sure "/usr/local/bin/wine64" exist
> 2. rm -rf ~/.wine
> 3. edit "node_modules/rcedit/lib/rcedit.js", change "wine" to "wine64" at line 42
> 4. download "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe", rename to "rcedit.exe" and replace "node_modules/rcedit/bin/rcedit.exe"
> 
> It works!!!

Please elaborate on Step 1 (I've heard of homebrew, but never used it: is "brew upgrade wine" a terminal command?)  Thanks!

**Comment by OlyDLG** [comment]
Also: where/how does one acquire homebrew: I tried Google, all I get is Homebrew CPU, and the App Store only gives me brewing apps. :-)

**Comment by jordanlewis** [comment]
@OlyDLG https://brew.sh/

**Comment by anishagg17** [comment]
> > > ... and replace "node_modules/rcedit/bin/rcedit.exe"  ...
> > 
> > 
> > can I ask what is the full path for that file?
> > thanks
> 
> /usr/local/lib/node_modules/nativefier/node_modules/rcedit/bin/rcedit.exe

This path doesn't exist on my pc, even after running `npm i -g rcedit`

**Comment by clintnetwork** [comment]
Good one, just use `wine64` instead!

**Comment by CommunistWeeb2** [comment]
> 1. brew upgrade wine, make sure "/usr/local/bin/wine64" exist
> 2. rm -rf ~/.wine
> 3. edit "node_modules/rcedit/lib/rcedit.js", change "wine" to "wine64" at line 42
> 4. download "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe", rename to "rcedit.exe" and replace "node_modules/rcedit/bin/rcedit.exe"
> 
> It works!!!

I can't find wine at line 42, however I can find it at line 40, is this right, or is my install wrong?
