### ISSUE TITLE
npm test did not pass 

### ISSUE THREAD

**Issue by sherebiahtishbi** [electron/node-rcedit#57]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\node-rcedit\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'mocha'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.16.3
4 verbose run-script [ 'premocha', 'mocha', 'postmocha' ]
5 info lifecycle rcedit@0.0.0-development~premocha: rcedit@0.0.0-development
6 info lifecycle rcedit@0.0.0-development~mocha: rcedit@0.0.0-development
7 verbose lifecycle rcedit@0.0.0-development~mocha: unsafe-perm in lifecycle true
8 verbose lifecycle rcedit@0.0.0-development~mocha: PATH: C:\node-rcedit\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\node-rcedit\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\node-rcedit\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Sherebyah Tisbi\AppData\Local\Microsoft\WindowsApps;C:\Users\Sherebyah Tisbi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sherebyah Tisbi\AppData\Roaming\npm
9 verbose lifecycle rcedit@0.0.0-development~mocha: CWD: C:\node-rcedit
10 silly lifecycle rcedit@0.0.0-development~mocha: Args: [ '/d /s /c', 'mocha test/*.js' ]
11 silly lifecycle rcedit@0.0.0-development~mocha: Returned: code: 3  signal: null
12 info lifecycle rcedit@0.0.0-development~mocha: Failed to exec mocha script
13 verbose stack Error: rcedit@0.0.0-development mocha: `mocha test/*.js`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (C:\node-rcedit\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\node-rcedit\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid rcedit@0.0.0-development
15 verbose cwd C:\node-rcedit
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\node-rcedit\\node_modules\\npm\\bin\\npm-cli.js" "run" "mocha"
18 verbose node v12.16.3
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 3
22 error rcedit@0.0.0-development mocha: `mocha test/*.js`
22 error Exit status 3
23 error Failed at the rcedit@0.0.0-development mocha script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]

**Comment by malept** [comment]
I can't reproduce this on Windows 10 Home, running Node 12.15.0. The testsuite runs fine for me.

Please paste the output of running `yarn test` instead of the NPM log.
