### ISSUE TITLE
Fatal error: Unable to set icon

### ISSUE THREAD

**Issue by importre** [electron/node-rcedit#6]
Hi.

Packing [my electron app](https://github.com/importre/gpmp) for win32, I got `Fatal error`.
Currently, [no icon for win32](https://github.com/importre/gpmp/blob/master/build_common.sh#L2-L6).
## error message

After set `icon` to `"assets/app.icns"` for win32,

```
$ npm run build
...
Packaging app for platform win32 ia32 using electron v0.28.3
fixme:heap:HeapSetInformation 0x0 1 0x0 0
Fatal error: Unable to set icon
 undefined
```
## wine

I've already installed wine using brew.
## env

OSX-10.10.3
wine-1.6.2

**Comment by unindented** [comment]
Thanks for reporting. I'll try to repro with your project this weekend when I have some free time.

**Comment by haoxins** [comment]
+1 for this

* Env 
  - win10, win7

the args pass to rcedit include `--set-icon mypath.ico`, but not work.

**Comment by seanzer** [comment]
When running from node, I get "Fatal error: Unable to commit changes"

When I run from command line, I get no output, but the icon is not set.
`rcedit production\layout\electron.exe --set-icon icon.ico`

**Comment by Rensdn** [comment]
rcedit.exe failed with exit code 1. Reserved header is not 0 or image type is not icon for 'p'

**Comment by ikiK-CRO** [comment]
Still same problem. I have windows 10, and OSX, and I can not set icon on ether system for Windows build.

**Comment by malept** [comment]
I'm closing this because the latest version of rcedit (which node-rcedit vendors) gives a reason why the icon can't be set.
