### ISSUE TITLE
Error about GetCurrentPackgeId on Wine 64

### ISSUE THREAD

**Issue by gyzerok** [electron/node-rcedit#64]
Hello!

I am trying to use `rcedit@2.2.0` on macOS Catalina with `wine64`. And here is what happens.

```
$ wine64 ./node_modules/rcedit/bin/rcedit-x64.exe ./build/my_app.exe --set-icon ./win_icon.ico 
0009:fixme:ver:GetCurrentPackageId (0x21fd10 0x0): stub
```

Do you have any suggestions on how I can solve it?

**Comment by malept** [comment]
This indicates that there's an unimplemented function in Wine used, there's nothing that can be done in this Node module (or in `rcedit`) about it.
