### ISSUE TITLE
On how to use rcedit

### ISSUE THREAD

**Issue by hhammoud01** [electron/node-rcedit#8]
Hello guys,

I am not quite familiar with npm. I installed it recently and run the command "npm install -g rcedit" to install rcedit. But how do I use it ? 

Thank you,
Regards,

**Comment by kevinsawicki** [comment]
This library exports a function that can be called to adjust the settings of a `.exe` file.

See the README for more details https://github.com/electron/node-rcedit#rceditexepath-options-callback

Closing this out.
