### ISSUE TITLE
Wrong `rcredit` executable is resolved on Apple Silicon platforms (ARM64).

### ISSUE THREAD

**Issue by mn4367** [electron/node-rcedit#83]
I've seen this while using Electron Packager to build a Windows version of an Electron app with a custom app icon on a Mac with Apple Silicon (M1) . `wine-stable` is installed via Homebrew and works properly. The reason is that node-rcedit only checks for the `x64` architecture to execute `rcedit-x64.exe` instead of `rcedit.exe`. This may also fail on other ARM64 platforms where Wine/node-rcedit is used.

To fix it, this line

https://github.com/electron/node-rcedit/blob/488329ac3eb20afe46094dbf6d36376d7f0dbb02/lib/rcedit.js#L9

should be

```javascript
    const rceditExe = process.arch === 'x64' || process.arch === 'arm64' ? 'rcedit-x64.exe' : 'rcedit.exe'
```

Since node-rcedit now uses [cross-spawn-windows-exe](https://github.com/malept/cross-spawn-windows-exe) to run Wine a similar fix seems to be needed [there](https://github.com/malept/cross-spawn-windows-exe/blob/8b3a821e2a5c2e74512a9a6d72ed6ea6c53262fa/src/exe.ts#L39) (I think).

\
Maybe this should also be backported to v2.3.0 since this is the version Electron Packager currently uses. The changes there would be

https://github.com/electron/node-rcedit/blob/ee4e10a57d4f292d32b306e141bdb6edde1f7ccb/lib/rcedit.js#L10

to

```javascript
      let rcedit = path.resolve(__dirname, '..', 'bin', process.arch === 'x64' || process.arch === 'arm64' ? 'rcedit-x64.exe' : 'rcedit.exe')
```

and

https://github.com/electron/node-rcedit/blob/ee4e10a57d4f292d32b306e141bdb6edde1f7ccb/lib/rcedit.js#L40

to

```javascript
    rcedit = process.arch === 'x64' || process.arch === 'arm64' ? 'wine64' : 'wine'
```

**Comment by hussa6** [comment]
That's correct, I also went down a similar route, changing x64 to arm64 for M1 macs.

**Comment by mn4367** [comment]
@malept thanks for fixing this!
